title: "{dp} · doble página"
author:
  name: "Herbert Spencer"
description: Un espacio para la experimentación y la reflexión
locale: es
baseurl: "" # Deja esto vacío si es tu sitio principal
url: "https://herbertspencer.net"
feed:
  path: "feed.xml"
future: true

# Configuración de construcción
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  parse_span_html: true
  html_to_native: false

safe: false # Permite el uso de plugins personalizados
plugins_dir: _plugins   # Especifica el directorio de plugins (si se requiere)

destination: docs      # Genera los archivos estáticos en /docs
permalink: /:categories/:title/

build:
  sass:
    style: compressed

# Plugins de Jekyll (instalar en el Gemfile también)
plugins:
  - jekyll-sass-converter
  - jekyll-assets

# Sass
sass:
  load_paths: 
    - .
    - _sass
  style: compressed
  syntax: scss  

# Directorios personalizados
include:
  - _sass
  - assets/css
  - _layouts
  - sitemap.xml

# Excluir archivos y carpetas
exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Colecciones
collections:
  pages:
    output: true
    permalink: /pages/:title/
  posts:
    output: true
    permalink: /posts/:title/

# Valores predeterminados para el front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "post"

# no github default theme
theme: null